### ISSUE TITLE
Custom show label for tree

### ISSUE THREAD

**Issue by Luu-Gia-Khanh** [duzhijie317/vue-virtual-scroll-tree#1]
Hi @duzhijie317,
it is a good package for me, but it would be good if you added a slot with slotPros for the label tree (the dev can custom show the label instead of only the name).
Thanks!!

**Comment by duzhijie317** [comment]
ok I'll add it and inform you

Luu-Gia-Khanh ***@***.***> 于2024年1月24日周三 18:45写道：
